const values = {
  SUCCESS: 0,
  ERROR_FAIL: 1,
  ERROR_PARAM_EMPTY: 101,
  ERROR_PARAM_INVALID: 102,
  ERROR_CODE_INVALID: 103,
  ERROR_OBJECT_EXIST: 201,
  ERROR_OBJECT_NOT_EXIST: 202,
  ERROR_USER_NOT_EXIST: 203,
  ERROR_OBJECT_NOT_BIND: 204,
  ERROR_AUTH_FAIL: 301,
  ERROR_PERMISSION_DENIED: 302,
  ERROR_CREATE_FAIL: 401,
  ERROR_UPDATE_FAIL: 402,
  ERROR_DELETE_FAIL: 403,
  ERROR_NOT_FOUND: 404,
  ERROR_TOKEN_TIMEOUT_CODE: 405,
  ERROR_DOWNGRADE: 406,
  ERROR_SERVER_ERROR_CODE: 500,
  ERROR_CAPTCHA_INVALID: 901,
  ERROR_UNKNOWN: 902,
  ERROR_FILE_NOT_FOUND: 903,
  CUSTOM_NOTIFY: 1024,
};

export const responseStatus = {
  [values.SUCCESS]: '成功',
  [values.ERROR_FAIL]: '未知错误，失败',
  [values.ERROR_PARAM_EMPTY]: '参数为必填',
  [values.ERROR_PARAM_INVALID]: '参数无效',
  [values.ERROR_CODE_INVALID]: '验证码无效',
  [values.ERROR_OBJECT_EXIST]: '对象已存在',
  [values.ERROR_OBJECT_NOT_EXIST]: '对象不存在',
  [values.ERROR_USER_NOT_EXIST]: '用户名不存在或密码错误',
  [values.ERROR_OBJECT_NOT_BIND]: '用户未绑定',
  [values.ERROR_AUTH_FAIL]: '未授权操作',
  [values.ERROR_PERMISSION_DENIED]: '无权限操作',
  [values.ERROR_CREATE_FAIL]: '创建失败',
  [values.ERROR_UPDATE_FAIL]: '更新失败',
  [values.ERROR_DELETE_FAIL]: '删除失败',
  [values.ERROR_NOT_FOUND]: '资源没找到',
  [values.ERROR_TOKEN_TIMEOUT_CODE]: 'token过期或者无效',
  [values.ERROR_DOWNGRADE]: '网络异常，请稍后重试',
  [values.ERROR_SERVER_ERROR_CODE]: '服务器错误',
  [values.ERROR_CAPTCHA_INVALID]: '验证码无效',
  [values.ERROR_UNKNOWN]: '系统繁忙，请稍后再试....',
  [values.ERROR_FILE_NOT_FOUND]: '你要读取的资源找不到',
  [values.CUSTOM_NOTIFY]: '返回自定义提示',
};

export default { ...values, responseStatus };
